import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import "../../globals.css";
import { AppSidebar } from "@/components/layout/Sidebar";

export const metadata: Metadata = {
  title: "Financial Sass ERP system",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <main className="border-2 border-red-700 flex min-h-screen w-full" >
        <AppSidebar />
        <div className="flex flex-1 flex-col">
          <SidebarTrigger />
          {children}
        </div>
      </main>
    </SidebarProvider>
  );
}
