import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import "../../globals.css";
import { AppSidebar } from "@/components/layout/Sidebar";

export const metadata: Metadata = {
  title: "Financial Sass ERP system",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider defaultOpen={true}>
      <AppSidebar />
      <main className="flex flex-1 flex-col min-h-screen w-full">
        <div className="fixed top-4 right-4 z-40 md:hidden">
          <SidebarTrigger className="bg-slate-900 text-white hover:bg-slate-800 border-0" />
        </div>
        <div className="flex-1">
          {children}
        </div>
      </main>
    </SidebarProvider>
  );
}
